package mx.edu.utez.jyps.data.model

/**
 * Request payload to initiate a password recovery flow.
 *
 * @property correo The institutional email address to which the token will be sent.
 */
data class PasswordTokenRequest(
    val correo: String
)

/**
 * Request payload to set or reset a user account password using a unique token.
 *
 * @property token The access token generated by the server and sent via email.
 * @property password The new raw string password to be established.
 */
data class PasswordSetupRequest(
    val token: String,
    val password: String
)

/**
 * Generic response schema for operations that primarily return a status message.
 *
 * @property mensaje Descriptive success or informative message from the server.
 */
data class GenericMessageResponse(
    val mensaje: String
)

/**
 * Detailed information returned after validating an access token for password setup.
 *
 * @property nombreCompleto Real name of the user associated with the token.
 * @property correo Institutional email address of the account.
 */
data class TokenValidationResponse(
    val nombreCompleto: String,
    val correo: String? = null
)
